### ISSUE TITLE
Exercise set 19

### ISSUE THREAD

**Issue by smattingly** [csci320/weintraubm320#21]
Don't type the `db.query(...` etc. Only the part that you would type into the web form (the part that becomes the value of `student.email`.)

**Comment by smattingly** [comment]
Two of your "injected" queries have syntax errors in them (nothing to do with injection; just test the "attack" queries as stand alone statements).

BTW, the lines should start with double, not single, quotes. Minor, but would be necessary to make the attack work.

**Comment by Weintraubm** [comment]
@smattingly  i fixed 19 https://github.com/csci320/weintraubm320/blob/master/exercise19%201-4.txt

**Comment by smattingly** [comment]
👍
