### ISSUE TITLE
student_major table

### ISSUE THREAD

**Issue by smattingly** [csci320/weintraubm320#8]
https://github.com/csci320/weintraubm320/blob/d9d6b50d7b7978e537e6286caafa15aa3cfa2b6c/exercise5-5.txt#L3

Please include the CREATE TABLE statement. 

Why would `student_major` have a gender column? What fact does a row like `('ccadillac@dewv.net', 'Management', 'Men')` express?

Data for student majors should come from the `visit` table.

**Comment by Weintraubm** [comment]
so should i delete the table and remake it?
@smattingly

**Comment by smattingly** [comment]
Yes.

**Comment by smattingly** [comment]
FYI, haven't seen a change for this. It's the only thing remaining for Exercise set 5 credit.
